title: ISSM Documentation
description: Custom template for the ISSM Documentation Jeykll site using the Just the Docs theme
theme: just-the-docs

url: https://issmteam.github.io/ISSM-Documentation/

# Site logo
logo: "/assets/img/issm-logo.png"

# Site favicon
favicon_ico: "/assets/img/favicon.ico"

# Aux links
aux_links:
  "ISSM on GitHub":
    - "https://github.com/ISSMteam/ISSM"
aux_links_new_tab: true

# Footer content
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ISSMteam/ISSM-Documentation"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "edit"

callouts:
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  highlight:
    color: yellow
