title: ISSM Documentation
description: Documentation page for the Ice-Sheet and Sea-level System Model (ISSM). Included are instructions for installation and use of ISSM, development status and forecast, as well as information about how ISSM used and the team behind it.
theme: just-the-docs

url: https://issmteam.github.io/ISSM-Documentation/

color_scheme: issm

# Site logo
logo: "/assets/img/issm-logo.png"

# Site favicon
favicon_ico: "/assets/img/favicon.ico"

# Aux links
aux_links:
  "ISSM on GitHub":
    - "https://github.com/ISSMteam/ISSM"
  "ISSM forum":
    - "https://issm.ess.uci.edu/forum/"
aux_links_new_tab: true

# Footer content
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ISSMteam/ISSM-Documentation"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "edit"

callouts:
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  highlight:
    color: yellow
