# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# TODO:
# - Add build step to remove duplicate DOI's
#
name: Update Publications Page

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/publications.yml"
      - "docs/about-issm/publications/bin/**"
      - "docs/about-issm/publications/doi/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to write back to repo
permissions:
  contents: write

env:
  TARGET: "./index.md"

jobs:
  complete:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/about-issm/publications
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Publications Page
        run: |
          ./bin/generate_publications_page.sh > ${{ env.TARGET }}
      - name: Commit and Push Updated Publications Page
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add ${{ env.TARGET }}
          git commit -m 'CHG: Updated Publications page'
          git push
